version: 1
rules:
    - id: openapi.operation-summary
      check: openapi.operation-summary
      severity: warning
    - id: openapi.operation-description
      check: openapi.operation-description
      severity: warning
    - id: openapi.parameter-description
      check: openapi.parameter-description
      severity: warning
    - id: openapi.schema-description
      check: openapi.schema-description
      severity: warning
    - id: openapi.request-response-example
      check: openapi.request-response-example
      severity: warning
    - id: openapi.tags-defined
      check: openapi.tags-defined
      severity: warning
    - id: openapi.info-description
      check: openapi.info-description
      severity: warning
